### PR TITLE
add emacs

### PR DESCRIPTION
**Pull request by m2Giles**
Does not add on coreos:next. Emacs pulls in a lot of packages via weak dependencies.

### CODE REVIEW

**Comment by travier** [comment]
The dependency on `kernel-headers` is not great here :/

**Comment by m2Giles** [comment]
Will poke around looking at how that's getting pulled in. Assuming it's a dependency of one the build tools that emacs pulls in

**Comment by m2Giles** [comment]
Dependency goes:
emacs-common -> libgccjit -> gcc -> glibc-devel -> kernel-headers

This is unfortunate.

**Comment by travier** [comment]
Not sure what to do. Does the emacs Flatpak has those as well? Are they really needed at runtime?

**Comment by m2Giles** [comment]
Flatpaks emacs has gcc and glibc-devel equivalent in the freedesktop-sdk.

Kernel-headers appears to be fedora.

**Comment by travier** [comment]
Alright, let's start with that, we can always improve later.

**Review by travier — APPROVED** [review]

**Pull request merged**
