### PR TITLE
Add the CNI plugins

### PR DESCRIPTION
**Pull request by cverna**
This is needed to run CNI plugin like flannel on kubernetes.

### CODE REVIEW

**Comment by travier** [comment]
Thanks! I'm wondering if maybe we should add those to the existing cri-o or kubernetes sysexts directly?

**Comment by travier** [comment]
It pulls only this package so looks good. We could consider including it in the Kubernetes package (and maybe fold the cri-o & kubernetes into a single one) but having each be separated is also good for now.

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
I didn't look close enough but those are already included in the kubernetes sysexts via dependencies, albeit not explicitly (but we can change that as well). Any specific reason to have a standalone one?

**Comment by cverna** [comment]
> I didn't look close enough before but those are already included in the kubernetes sysexts via dependencies, albeit not explicitly (but we can change that as well). Any specific reason to have a standalone one?

Hmm, ok I didn't try that. I just noticed that the package wasn't installed on FCOS (using rpm -qa) but didn't think about it being pulled in via sysexts. 

Closing this PR 😄

**Pull request closed without merging**
